### ISSUE TITLE
Latest changes aren't published

### ISSUE THREAD

**Issue by zdoc01** [xpl/crx-hotreload#6]
Heya! Thanks for making this =D. It doesn't look like the latest changes (from [this commit](https://github.com/xpl/crx-hotreload/commit/09c418a7aa740f726b98bd4f6d9992d63646eddf#diff-c8fd6a4f039326a1fa0b4b02c4c6f281)) have been published to `npm`. Do you have plans to do that anytime soon?

**Comment by xpl** [comment]
@zdoc01 Done! Thanks for the heads up.

**Comment by zdoc01** [comment]
Thanks for your help!
