### ISSUE TITLE
Make hot-reload `import`able from the npm package

### ISSUE THREAD

**Issue by iamogbz** [xpl/crx-hotreload#9]
Make it `import`able from the [NPM module](https://www.npmjs.com/package/crx-hotreload), as it's suggested [here](https://stackoverflow.com/questions/2963260/how-do-i-auto-reload-a-chrome-extension-im-developing/40454227#comment79536659_40454227).

Tested this and it worked! 🎉 

```js
import "crx-hotreload";
```

I think the [`Readme`](/xpl/crx-hotreload/readme.md) can be updated!

**Comment by xpl** [comment]
Thank you for the feedback! I'll make changes.

**Comment by AudereSemper** [comment]
is there a place where i need to

import "crx-hotreload" ? 

or every folder is the same ? Could you please more specific about this step ?
